### ISSUE TITLE
feature request: fully expand merges and anchors

### ISSUE THREAD

**Issue by nelsonihc** [inobelar/yaml_interpolate#1]
Hi, thanks for developing the tool. 

Is it possible to add a flag to fully expand merges and anchors? This tool is great for "rendering" complex .yaml setups and this feature would replace another yaml tool that I'm using to do this expansion.

this behavior is featured in the ruamel.yaml library (python)
`$ yaml merge-expand input.yaml output.yaml`

Example input:
```
sitename: website

default: &DEFAULT
  URL: {{sitename}}.com
  mode: production  
  site_name: Website
  some_setting: h2i8yiuhef
  some_other_setting: 3600

development:
  <<: *DEFAULT
  URL: {{sitename}}.local
  mode: dev

test:
  <<: *DEFAULT
  URL: test.{{sitename}}.qa
  mode: test
```

Example output:
```
sitename: website

default:
  URL: website.com
  mode: production  
  site_name: Website
  some_setting: h2i8yiuhef
  some_other_setting: 3600

development:
  URL: website.local
  mode: dev
  site_name: Website
  some_setting: h2i8yiuhef
  some_other_setting: 3600

test:
  URL: test.website.qa
  mode: test
  site_name: Website
  some_setting: h2i8yiuhef
  some_other_setting: 3600
```
